version: '3'

services:
  database:
    restart: always
    image: postgres:13.1
    hostname: database
    volumes:
      - market_postgres_data:/var/lib/postgresql/data:delegated
    ports:
      - 5432:5432
    networks:
      - net
    env_file:
      - .env

  skyeng-server:
    image: scp2020:latest
    hostname: skyeng-server
    ports:
      - 8080:8080
    env_file:
      - .env
    networks:
      - net

networks:
  net:

volumes:
  market_postgres_data:
